### ISSUE TITLE
Failed to compile issue for example

### ISSUE THREAD

**Issue by brianpham** [kennetpostigo/react-google-login-component#14]
Hi, I am seeing this error when trying to start the example. I was able to fix the issue by updating the App.js file importing GoogleLogin from react-google-login-component.

```
Error in /Users/bpham/Dev/react-google-login-component/dist/react-google-login-component.js
Module not found: 'react' in /Users/bpham/Dev/react-google-login-component/dist

 @ /Users/bpham/Dev/react-google-login-component/dist/react-google-login-component.js 3:27-43
```

**Comment by koss-lebedev** [comment]
hi @brianpham ,

it works with the reference to `dist` version in import statement, too, you just need to run `npm install react` first. React is listed as a peer dependency so it doesn't get installed automatically when you run `npm install`.

**Comment by kennetpostigo** [comment]
@brianpham like @koss-lebedev said React must be installed in order for the login component to work. 
just in case try the following commands:
```
rm -rf node_modules
npm install react react-google-login-component
npm install
```

**Comment by brianpham** [comment]
Thanks for the tip. Working now 👍
