### ISSUE TITLE
Invalid Scopes

### ISSUE THREAD

**Issue by graemeb52096** [kennetpostigo/react-google-login-component#16]
Are there any special naming conventions for defining scope? When i try to use drive as an additional scope to profile, I get an invalid scope error from google.

**Comment by Maggicorp** [comment]
Similar question, I would like to get it to return all the user information (given_name, family_name), ect.

**Comment by koss-lebedev** [comment]
Hey guys, `scope` value should be a space-delimited string with valid scope names.

**Comment by Maggicorp** [comment]
Yep, but I find passing in profile does not return first name, last name or profile picture, which is supposed to be part of basic profile. Any idea on how to get it to return those fields as well?  I feel like profile should return it but it doesn't.

**Comment by koss-lebedev** [comment]
Hey @Maggicorp , thanks for the feedback. Now you can update to version 0.9.1 and set component's property `fetchBasicProfile` to `true`, that should do the trick :)
