### ISSUE TITLE
invalid_client error

### ISSUE THREAD

**Issue by DigitalTheorist** [kennetpostigo/react-google-login-component#17]
popup worked but returned an invalid client error. Cut an paste code from the "usage" section of the NPM page. Any ideas on resolving this? Thanks! 

<img width="994" alt="googleloginreact" src="https://user-images.githubusercontent.com/24688589/31064412-c26fd2e8-a6f0-11e7-9329-18c3e62de60a.png">

**Comment by koss-lebedev** [comment]
Hey @DigitalTheorist ,

for `socialId` property you need to supply your own google app id.
