### ISSUE TITLE
Doesn't get name

### ISSUE THREAD

**Issue by shavidzet** [kennetpostigo/react-google-login-component#22]
fetching only email, but when I try to get user name it returns undefined.
```js
  responseGoogle (response) {
    const profile = response.getBasicProfile()
    console.log(profile.getName()) // always returns undefined
  }
```
Does someone has same problem?

**Comment by gravyplaya** [comment]
have the same issue. This should return the same as from Google but it does not.. CANT USE!

**Comment by adohyung** [comment]
I think It's a documentation issue. Have you tried to pass a `fetchBasicProfile` props to `true`?
Then It should work as you expected.

https://github.com/kennetpostigo/react-google-login-component/blob/ef9524a26da9914f0c1c925e04cd3531fe0b7694/src/GoogleLogin.js#L74

**Comment by adhrinae** [comment]
I think It's a documentation issue. Have you tried to pass the `fetchBasicProfile` props to `true`?
Then It should work as you expected.

https://github.com/kennetpostigo/react-google-login-component/blob/ef9524a26da9914f0c1c925e04cd3531fe0b7694/src/GoogleLogin.js#L74

**Comment by shavidzet** [comment]
@emaren84 agree it's a doc issue also.
I leave to use this repo because of support and docs

**Comment by kennetpostigo** [comment]
Hey @ShavidzeT , If you have thoughts about better documentation I would be open to accepting a PR

**Comment by arnaudmanaranche** [comment]
If you pass the props `fetchBasicProfile ` to `true` you will get the following user information : 

- ID
- Full name
- Given name
- Family Name
- Email

Thanks @adhrinae !
