### ISSUE TITLE
Component button set to `disabled: true` when navigating back to login page

### ISSUE THREAD

**Issue by Rahul-Krishnan** [kennetpostigo/react-google-login-component#23]
Hi, I am using React Router and Redux in my app, and the `<GoogleLogin />` component works fine when initially logging in. However, when I have a user redirected back to the login screen after logout, the Component state is set to `disabled: true`, even though I have explicitly passed props as `disabled: false`. Is anyone else having this issue, or know how to resolve it?

**Comment by koss-lebedev** [comment]
hey @Rahul-Krishnan , 

this was fixed in `0.9.2`, please update your version :)
