### ISSUE TITLE
Npm package page

### ISSUE THREAD

**Issue by Girardvjonathan** [kennetpostigo/react-google-login-component#3]
I don't know if this is the good place to raise the issue but in the npm package page for this plugin 
the exemple code following
 
`import GoogleLogin from 'react-google-login-component';`

should be replaced to :

`import { GoogleLogin } from 'react-google-login-component';`

**Comment by kennetpostigo** [comment]
@Girardvjonathan thanks will do, unless you want to submit a PR that makes the change? It's easy simple change and contribution

**Comment by Girardvjonathan** [comment]
@kennetpostigo I am not sure if there is any code change except the npm version. Your readme on github seem out of sync with the one on the npm website. See https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package 

Thanks anyway :smiley:
