### ISSUE TITLE
Popup blocked

### ISSUE THREAD

**Issue by darrenchiu** [kennetpostigo/react-google-login-component#4]
This package work perfectly and thanks! but it seems that the login popup is blocked by google chrome by default while the original google platform.js is not? Any idea in resolving this?

Thanks a lot!

**Comment by kennetpostigo** [comment]
Will take a look at this sometime this week. If it is urgent can you show me what the console shows you if anything at all? Best way to get this fixed quick is to submit a PR. I can't promise getting to this before this weekend.

**Comment by darrenchiu** [comment]
seems related to this:
[http://stackoverflow.com/questions/30125804/google-picker-auth-popup-is-being-blocked](http://stackoverflow.com/questions/30125804/google-picker-auth-popup-is-being-blocked)

> You will want to call gapi.auth.init. See the docs here: https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauthinit

>Initializes the authorization feature. Call this when the client loads to prevent popup blockers from blocking the auth window on gapi.auth.authorize calls.

**Comment by hmontes** [comment]
Same issue.

In console
```cb=gapi.loaded_0:99 Uncaught {error: "popup_blocked_by_browser"}```
