### ISSUE TITLE
Prevent submit

### ISSUE THREAD

**Issue by luisfuertes** [kennetpostigo/react-google-login-component#8]
Hi, your component works perfect, but i have GoogleLogin button in form and when i click it or press enter key, form do submit.

How can i prevent it?

**Comment by koss-lebedev** [comment]
hey @kennetpostigo ,

could you upload the latest version in NPM? In the newer version, it will be possible to add `type="button"` to prevent form submit issue mentioned above.

**Comment by kennetpostigo** [comment]
@koss-lebedev will publish by the end of the day. @luisfuertes @koss-lebedev sorry for the delay

**Comment by kennetpostigo** [comment]
@koss-lebedev you can now publish the changes to npm 🎉 and review PR's for both google and facebook login packages Thank you for helping maintain these projects!

**Comment by koss-lebedev** [comment]
hey @luisfuertes ,

you can update the component to v. 0.8.0 and supply `type="button"` to prevent form submit
